version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-helm.svg
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/andrewyuau/IIB-MQ](https://github.com/andrewyuau/IIB-MQ)
    git branch: >-
      [master](https://github.com/andrewyuau/IIB-MQ/tree/master)
toolchain:
  name: 'helm-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  repo:
    service_id: hostedgit
    parameters:
      repo_name: 'iib-mq-{{timestamp}}'
      repo_url: 'https://github.com/andrewyuau/IIB-MQ'
      type: clone
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: 'iib-mq-{{timestamp}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
